[theme]
base = "dark"
primaryColor = "#cfbcff"
backgroundColor = "#141218"
secondaryBackgroundColor = "#1d1b20"
textColor = "#e6e0e9"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
